### PR TITLE
Feat/checkout page

### PR DESCRIPTION
**Pull request by trucho1001**
Done basically to save the data! check and cmt guys!!

### CODE REVIEW

**Comment by trucho1001** [comment]
omh, conflicts :((((((

**Review by zevik7 — APPROVED** [review]
Ok I fixed conflick

**Review by trucho1001 — COMMENTED** [review]
So great!!!1

**Review by nguyendang127 — APPROVED** [review]

**Comment by trucho1001** [comment]
[Feat/checkout-page](https://trello.com/c/nSzvanGy/30-feat-checkout-page)

**Pull request merged**
